import { createFileRoute } from "@tanstack/react-router";
import { lazy, Suspense } from "react";
import { ClientOnly } from "@tanstack/react-router";
import { Section, Reveal } from "@/components/site/Section";
import { architectureDiagram, dependencyDiagram } from "@/data/demo";

const Mermaid = lazy(() => import("@/components/site/Mermaid"));

export const Route = createFileRoute("/architecture")({
  head: () => ({
    meta: [
      { title: "System Architecture & Dependency Graph | CodeMentor AI" },
      {
        name: "description",
        content:
          "The CodeMentor AI pipeline from GitHub URL to cited answer: ingestion, AST chunking, embeddings, hybrid retrieval, LLM, sandbox and evaluator.",
      },
      { property: "og:title", content: "CodeMentor AI — System Architecture" },
      {
        property: "og:description",
        content:
          "Auto-generated Mermaid architecture diagram and module dependency graph for the platform.",
      },
    ],
  }),
  component: ArchitecturePage,
});

const pipeline = [
  { step: "01", title: "Clone & filter", body: "GitPython shallow-clones the repo and drops vendor directories." },
  { step: "02", title: "Parse", body: "Tree-sitter builds an AST per file across five languages." },
  { step: "03", title: "Chunk", body: "Chunks follow function and class boundaries, keeping line metadata." },
  { step: "04", title: "Embed", body: "Each chunk becomes a 384-dimension vector." },
  { step: "05", title: "Retrieve", body: "Cosine similarity and BM25 scores merge into one ranking." },
  { step: "06", title: "Answer", body: "The LLM streams a response carrying file and line citations." },
];

function DiagramFallback() {
  return (
    <div className="h-64 animate-pulse rounded-xl border border-border bg-code" />
  );
}

function ArchitecturePage() {
  return (
    <>
      <Section
        eyebrow="Module D"
        title="System architecture"
        description="Generated by the LLM from the file tree and import graph, then rendered as Mermaid in the browser."
      >
        <Reveal>
          <ClientOnly fallback={<DiagramFallback />}>
            <Suspense fallback={<DiagramFallback />}>
              <Mermaid chart={architectureDiagram} />
            </Suspense>
          </ClientOnly>
        </Reveal>
      </Section>

      <Section
        eyebrow="Pipeline"
        title="From URL to cited answer"
        className="border-y border-border bg-surface/40"
      >
        <div className="grid gap-px overflow-hidden rounded-xl border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">
          {pipeline.map((p) => (
            <div key={p.step} className="bg-surface p-5">
              <span className="font-mono text-xs text-primary">{p.step}</span>
              <h3 className="mt-1.5 text-sm font-semibold">{p.title}</h3>
              <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{p.body}</p>
            </div>
          ))}
        </div>
      </Section>

      <Section
        eyebrow="Dependency graph"
        title="Module dependencies extracted from imports"
        description="The same generator produces a dependency view so reviewers can see which layers depend on which."
      >
        <Reveal>
          <ClientOnly fallback={<DiagramFallback />}>
            <Suspense fallback={<DiagramFallback />}>
              <Mermaid chart={dependencyDiagram} />
            </Suspense>
          </ClientOnly>
        </Reveal>
      </Section>
    </>
  );
}
